import * as vscode from "vscode";
import * as path from "path";
import { stringify as stringifyYaml } from "yaml";
import { getBuiltinDefaultDocTypes } from "../crawler/docTypes";
import { DocTypeDefinition } from "../model/types";

function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

function substitute(text: string, tokens: Record<string, string>): string {
  return Object.entries(tokens).reduce(
    (acc, [key, value]) => acc.split(`{{${key}}}`).join(value),
    text
  );
}

async function readTemplate(extensionUri: vscode.Uri, relPath: string): Promise<string> {
  const uri = vscode.Uri.joinPath(extensionUri, "templates", relPath);
  const bytes = await vscode.workspace.fs.readFile(uri);
  return Buffer.from(bytes).toString("utf8");
}

async function fileExists(uri: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(uri);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(uri: vscode.Uri): Promise<void> {
  try {
    await vscode.workspace.fs.createDirectory(uri);
  } catch {
    // best-effort; a pre-existing file at this path would surface later on write anyway
  }
}

async function pickFolders(
  folders: readonly vscode.WorkspaceFolder[]
): Promise<vscode.WorkspaceFolder[] | undefined> {
  const picks = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, folder: f, picked: true })),
    {
      canPickMany: true,
      placeHolder: "Select the repo(s) that make up this product",
    }
  );
  return picks?.map((p) => p.folder);
}

async function pickRoot(
  folders: readonly vscode.WorkspaceFolder[]
): Promise<vscode.WorkspaceFolder | undefined> {
  const pick = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, folder: f })),
    { placeHolder: "Which repo holds the mission/epics (the 'root')?" }
  );
  return pick?.folder;
}

/** `track:` list for a repo's generated `.specmesh.yml` -- root also gets mission/epic, since those live there. */
function buildSpecmeshYml(isRoot: boolean): string {
  const track: DocTypeDefinition[] = isRoot
    ? [
        { type: "mission", label: "Mission", glob: "docs/mission.md" },
        { type: "epic", label: "Epics", glob: "docs/epics/EPIC-*.md" },
        ...getBuiltinDefaultDocTypes(),
      ]
    : getBuiltinDefaultDocTypes();

  const header =
    "# specmesh per-repo config -- auto-generated by 'specmesh: Scaffold Spec-Driven Development Structure'.\n" +
    "# Edit freely: add/remove doc types, or add an 'exclude' list to any entry. See specmesh's README for the schema.\n";
  return header + stringifyYaml({ track });
}

/**
 * Scaffolds the mission → epic → FR/ADR/reference spec-driven-development structure (docs/mission.md,
 * docs/spec-driven-development.md, docs/epics/, per-repo docs/adr, docs/reference, .github/instructions,
 * .github/skills/{new-feature,change-request}, .github/copilot-instructions.md) across the workspace.
 * Never overwrites a file that already exists.
 */
export async function scaffoldSdlc(
  context: vscode.ExtensionContext,
  outputChannel: vscode.OutputChannel
): Promise<void> {
  const allFolders = vscode.workspace.workspaceFolders ?? [];
  if (allFolders.length === 0) {
    vscode.window.showWarningMessage("specmesh: open a workspace folder first.");
    return;
  }

  const picked =
    allFolders.length === 1 ? allFolders : await pickFolders(allFolders);
  if (!picked || picked.length === 0) {
    return;
  }

  const root = picked.length === 1 ? picked[0] : await pickRoot(picked);
  if (!root) {
    return;
  }

  const productName = await vscode.window.showInputBox({
    prompt: "Product name (used in mission.md and copilot-instructions.md)",
    value: root.name,
  });
  if (!productName) {
    return;
  }

  const repoLayout = picked
    .map((f) => `- \`${f.name}\`${f === root ? " — mission/epic root" : ""}`)
    .join("\n");

  const created: string[] = [];
  const skipped: string[] = [];

  const writeIfMissing = async (uri: vscode.Uri, content: string): Promise<void> => {
    if (await fileExists(uri)) {
      skipped.push(uri.fsPath);
      return;
    }
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, "utf8"));
    created.push(uri.fsPath);
  };

  // Root-only artifacts: mission.md, spec-driven-development.md, docs/epics/
  const missionUri = vscode.Uri.joinPath(root.uri, "docs/mission.md");
  const sddUri = vscode.Uri.joinPath(root.uri, "docs/spec-driven-development.md");

  await writeIfMissing(
    missionUri,
    substitute(await readTemplate(context.extensionUri, "mission.md"), { PRODUCT_NAME: productName })
  );
  await writeIfMissing(
    sddUri,
    substitute(await readTemplate(context.extensionUri, "spec-driven-development.md"), {
      PRODUCT_NAME: productName,
      REPO_LAYOUT: repoLayout,
    })
  );
  await ensureDir(vscode.Uri.joinPath(root.uri, "docs/epics"));

  const copilotInstructionsTemplate = await readTemplate(context.extensionUri, "copilot-instructions.md");
  const newFeatureTemplate = await readTemplate(context.extensionUri, "skills/new-feature/SKILL.md");
  const changeRequestTemplate = await readTemplate(context.extensionUri, "skills/change-request/SKILL.md");

  // Per-repo artifacts (every selected repo, including root)
  for (const folder of picked) {
    await ensureDir(vscode.Uri.joinPath(folder.uri, "docs/adr"));
    await ensureDir(vscode.Uri.joinPath(folder.uri, "docs/reference"));
    await ensureDir(vscode.Uri.joinPath(folder.uri, ".github/instructions"));

    const missionRel = toPosix(path.relative(folder.uri.fsPath, missionUri.fsPath));
    const sddRel = toPosix(path.relative(folder.uri.fsPath, sddUri.fsPath));
    const epicsRel = toPosix(
      path.relative(folder.uri.fsPath, vscode.Uri.joinPath(root.uri, "docs/epics").fsPath)
    );

    const tokens = {
      PRODUCT_NAME: productName,
      REPO_LAYOUT: repoLayout,
      MISSION_DOC_REL: missionRel,
      SDD_DOC_REL: sddRel,
      EPICS_DIR_REL: epicsRel,
    };

    await writeIfMissing(
      vscode.Uri.joinPath(folder.uri, ".github/copilot-instructions.md"),
      substitute(copilotInstructionsTemplate, tokens)
    );
    await writeIfMissing(
      vscode.Uri.joinPath(folder.uri, ".github/skills/new-feature/SKILL.md"),
      substitute(newFeatureTemplate, tokens)
    );
    await writeIfMissing(
      vscode.Uri.joinPath(folder.uri, ".github/skills/change-request/SKILL.md"),
      changeRequestTemplate
    );
    await writeIfMissing(vscode.Uri.joinPath(folder.uri, ".specmesh.yml"), buildSpecmeshYml(folder === root));
  }

  outputChannel.clear();
  outputChannel.appendLine(
    `specmesh: scaffolded SDLC structure for ${picked.length} repo(s), root = ${root.name}.`
  );
  outputChannel.appendLine(`Created ${created.length} file(s):`);
  created.forEach((p) => outputChannel.appendLine(`  + ${p}`));
  if (skipped.length > 0) {
    outputChannel.appendLine(`Skipped ${skipped.length} already-existing file(s) (left untouched):`);
    skipped.forEach((p) => outputChannel.appendLine(`  = ${p}`));
  }
  outputChannel.show();
}
