import * as vscode from "vscode";
import * as path from "path";
import { stringify as stringifyYaml } from "yaml";
import { DocTypeDefinition } from "../model/types";
import { PatternPack, getBuiltinPack } from "./patterns";
import { enableCentralTracking } from "../git/specRepo";

function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

function substitute(text: string, tokens: Record<string, string>): string {
  return Object.entries(tokens).reduce(
    (acc, [key, value]) => acc.split(`{{${key}}}`).join(value),
    text
  );
}

async function fileExists(uri: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(uri);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(uri: vscode.Uri): Promise<void> {
  try {
    await vscode.workspace.fs.createDirectory(uri);
  } catch {
    // best-effort; a pre-existing file at this path would surface later on write anyway
  }
}

async function pickFolders(
  folders: readonly vscode.WorkspaceFolder[]
): Promise<vscode.WorkspaceFolder[] | undefined> {
  const picks = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, folder: f, picked: true })),
    {
      canPickMany: true,
      placeHolder: "Select the repo(s) that make up this product",
    }
  );
  return picks?.map((p) => p.folder);
}

async function pickRoot(
  folders: readonly vscode.WorkspaceFolder[]
): Promise<vscode.WorkspaceFolder | undefined> {
  const pick = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, folder: f })),
    { placeHolder: "Which repo holds the charter/epics (the 'root')?" }
  );
  return pick?.folder;
}

/** `track:` list for a repo's generated `.specmesh.yml` -- root also gets the pack's root-only doc types. */
export function buildSpecmeshYml(pack: Pick<PatternPack, "docTypes" | "rootDocTypes">, isRoot: boolean): string {
  const track: DocTypeDefinition[] = isRoot ? [...pack.rootDocTypes, ...pack.docTypes] : pack.docTypes;

  const childrenHint =
    "#\n" +
    "# Nest a doc type under another in the tree with 'children': a matched instance nests under the parent\n" +
    "# instance sharing its directory + version (e.g. plan.v2.md nests under spec.v2.md in the same\n" +
    "# docs/FR-*/ folder) instead of listing under its own top-level category. Example:\n" +
    "#   - type: fr-spec\n" +
    "#     glob: \"docs/FR-*/spec.v*.md\"\n" +
    "#     children:\n" +
    "#       - type: fr-plan\n" +
    "#         glob: \"docs/FR-*/plan.v*.md\"\n";
  const reposHint = isRoot
    ? "#\n" +
      "# Declare child repos to auto-clone/sync them ('specmesh: Sync/Clone Repos'), and mirror this repo's own\n" +
      "# central .specmesh/spec.git remote so a fresh machine can bootstrap everything in one go. Example:\n" +
      "#   specRepoRemote: git@github.com:acme/product-specs.git\n" +
      "#   repos:\n" +
      "#     - name: product-api\n" +
      "#       remote: git@github.com:acme/product-api.git\n" +
      "#       path: ../product-api   # relative to this file; cloned here if missing\n"
    : "";

  const header =
    "# specmesh per-repo config -- auto-generated by 'specmesh: Scaffold Spec-Driven Development Structure'.\n" +
    "# Edit freely: add/remove doc types, or add an 'exclude' list to any entry. See specmesh's README for the schema.\n" +
    childrenHint +
    reposHint;
  return header + stringifyYaml({ track });
}

/**
 * Scaffolds the built-in `spec-driven-dev` documentation pattern (see [src/scaffold/patterns.ts](./patterns.ts))
 * across the workspace. Never overwrites a file that already exists.
 */
export async function scaffoldSdlc(
  context: vscode.ExtensionContext,
  outputChannel: vscode.OutputChannel
): Promise<void> {
  const allFolders = vscode.workspace.workspaceFolders ?? [];
  if (allFolders.length === 0) {
    vscode.window.showWarningMessage("specmesh: open a workspace folder first.");
    return;
  }

  const picked =
    allFolders.length === 1 ? allFolders : await pickFolders(allFolders);
  if (!picked || picked.length === 0) {
    return;
  }

  const root = picked.length === 1 ? picked[0] : await pickRoot(picked);
  if (!root) {
    return;
  }

  const productName = await vscode.window.showInputBox({
    prompt: "Product name (used in charter.md and copilot-instructions.md)",
    value: root.name,
  });
  if (!productName) {
    return;
  }

  const pack = getBuiltinPack(context.extensionUri);
  const repoLayout = picked
    .map((f) => `- \`${f.name}\`${f === root ? " — charter/epic root" : ""}`)
    .join("\n");

  const created: string[] = [];
  const skipped: string[] = [];

  const writeIfMissing = async (uri: vscode.Uri, content: string): Promise<void> => {
    if (await fileExists(uri)) {
      skipped.push(uri.fsPath);
      return;
    }
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, "utf8"));
    created.push(uri.fsPath);
  };

  const baseTokens = { PRODUCT_NAME: productName, REPO_LAYOUT: repoLayout };

  // Root-scope artifacts (dirs + templates), rendered once against the root repo. Their rendered locations are
  // remembered by relToken so per-repo templates below can reference them (e.g. "where is charter.md from here").
  const rootRelTargets = new Map<string, vscode.Uri>();

  for (const dir of pack.ensureDirs.filter((d) => d.scope === "root")) {
    const dirUri = vscode.Uri.joinPath(root.uri, dir.path);
    await ensureDir(dirUri);
    if (dir.relToken) {
      rootRelTargets.set(dir.relToken, dirUri);
    }
  }

  for (const tpl of pack.templates.filter((t) => t.scope === "root")) {
    const destUri = vscode.Uri.joinPath(root.uri, tpl.dest);
    await writeIfMissing(destUri, substitute(await pack.readTemplate(tpl.src), baseTokens));
    if (tpl.relToken) {
      rootRelTargets.set(tpl.relToken, destUri);
    }
  }

  // Per-repo artifacts (every selected repo, including root)
  for (const folder of picked) {
    for (const dir of pack.ensureDirs.filter((d) => d.scope === "perRepo")) {
      await ensureDir(vscode.Uri.joinPath(folder.uri, dir.path));
    }

    const relTokens: Record<string, string> = {};
    for (const [token, targetUri] of rootRelTargets) {
      relTokens[token] = toPosix(path.relative(folder.uri.fsPath, targetUri.fsPath));
    }
    const tokens = { ...baseTokens, ...relTokens };

    for (const tpl of pack.templates.filter((t) => t.scope === "perRepo")) {
      const destUri = vscode.Uri.joinPath(folder.uri, tpl.dest);
      await writeIfMissing(destUri, substitute(await pack.readTemplate(tpl.src), tokens));
    }

    await writeIfMissing(vscode.Uri.joinPath(folder.uri, ".specmesh.yml"), buildSpecmeshYml(pack, folder === root));
  }

  outputChannel.clear();
  outputChannel.appendLine(
    `specmesh: scaffolded "${pack.name}" SDLC structure for ${picked.length} repo(s), root = ${root.name}.`
  );
  outputChannel.appendLine(`Created ${created.length} file(s):`);
  created.forEach((p) => outputChannel.appendLine(`  + ${p}`));
  if (skipped.length > 0) {
    outputChannel.appendLine(`Skipped ${skipped.length} already-existing file(s) (left untouched):`);
    skipped.forEach((p) => outputChannel.appendLine(`  = ${p}`));
  }
  outputChannel.show();

  await enableCentralTracking(outputChannel, root);
}

